version: "3.8"

services:
  wolf-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "6000:6000"
    restart: always

    environment:
      - PYTHONUNBUFFERED=1

    volumes:
      - ./logs:/app/logs
      - ./.git:/app/.git:ro

    command: python src/bot.py
