# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "wolf-sparkling-wind-9638"
primary_region = "bom"

[build]
  builder = "dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python src/bot.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
